### PR TITLE
Add request body credential extraction

### LINKED ISSUE #9: Credentials extractor can use parsed body
Instead of writing a [separate content extractor](https://github.com/sparkphp/auth/blob/master/src/Credentials/JsonExtractor.php), it should be perfectly viable to use [`ContentHandler` to fill the parsed body of the request](https://github.com/sparkphp/spark/blob/master/src/Handler/ContentHandler.php) to simplify the code and make it more universal to any kind of content negotiation:

```php
$body = $request->getParsedBody();

if (empty($body[$this->identifier])) || empty(...)) {
    return null;
}

return new Credentials($body[$this->identifier], ...);
```

### PR DESCRIPTION
**Pull request by shadowhand**
When using content negotiation the parsed body of a request is filled.
This eliminates the need to have a separate JSON extractor.

Fixes #9

### CODE REVIEW

**Comment by shadowhand** [comment]
cc @elazar

**Comment by shadowhand** [comment]
I did not remove the `JsonExtractor`. Should I do that as part of this PR, or separately?

**Comment by elazar** [comment]
@shadowhand I'd say yes, go ahead and remove `JsonExtractor` as part of this PR. Also, submit a PR to update [this documentation section](https://github.com/sparkphp/spark/blob/master/docs/auth.md#credentials-extractor) accordingly.

**Comment by shadowhand** [comment]
@elazar documentation PR added.

**Comment by elazar** [comment]
:shipit:

**Comment by shadowhand** [comment]
Released in 0.3.0.

**Pull request merged**
